### ISSUE TITLE
Go to project root

### ISSUE THREAD

**Issue by kopach** [zoubin/vim-gotofile#1]
Hi. would it be possible to configure this plugin to search for files in project root directory? I have my webpack config set up in that way, that I can do absolute import (based on project root) instead of relative import. 
My project root directory is `src/`. I've tried to specify it like this: `'moduleDirectory': ['src']`, but it doesn't seem to work for me :/. Any ideas?

**Comment by zoubin** [comment]
You can try the `alias` option: https://github.com/zoubin/vim-gotofile#packagejson
